################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/AList_test_append.c \
../src/AList_test_append_first.c \
../src/AList_test_append_last.c \
../src/AList_test_append_left.c \
../src/AList_test_append_right.c \
../src/AList_test_as_array.c \
../src/AList_test_back.c \
../src/AList_test_count.c \
../src/AList_test_cursor_append_left.c \
../src/AList_test_cursor_append_right.c \
../src/AList_test_cursor_back.c \
../src/AList_test_cursor_dispose.c \
../src/AList_test_cursor_finish.c \
../src/AList_test_cursor_forth.c \
../src/AList_test_cursor_go.c \
../src/AList_test_cursor_index.c \
../src/AList_test_cursor_is_first.c \
../src/AList_test_cursor_is_last.c \
../src/AList_test_cursor_item_at.c \
../src/AList_test_cursor_item_next.c \
../src/AList_test_cursor_item_prev.c \
../src/AList_test_cursor_make.c \
../src/AList_test_cursor_off.c \
../src/AList_test_cursor_put_left.c \
../src/AList_test_cursor_put_right.c \
../src/AList_test_cursor_remove_at.c \
../src/AList_test_cursor_remove_at_and_dispose.c \
../src/AList_test_cursor_replace_at.c \
../src/AList_test_cursor_replace_at_and_dispose.c \
../src/AList_test_cursor_start.c \
../src/AList_test_dispose.c \
../src/AList_test_dispose_with_contents.c \
../src/AList_test_finish.c \
../src/AList_test_first.c \
../src/AList_test_forth.c \
../src/AList_test_go.c \
../src/AList_test_index.c \
../src/AList_test_is_empty.c \
../src/AList_test_is_first.c \
../src/AList_test_is_last.c \
../src/AList_test_item.c \
../src/AList_test_item_at.c \
../src/AList_test_item_next.c \
../src/AList_test_item_prev.c \
../src/AList_test_keep_first.c \
../src/AList_test_keep_first_and_dispose.c \
../src/AList_test_keep_last.c \
../src/AList_test_keep_last_and_dispose.c \
../src/AList_test_last.c \
../src/AList_test_make.c \
../src/AList_test_make_duplicate_from.c \
../src/AList_test_make_from.c \
../src/AList_test_make_from_array.c \
../src/AList_test_off.c \
../src/AList_test_p_clonable.c \
../src/AList_test_p_diterable.c \
../src/AList_test_p_indexable.c \
../src/AList_test_p_iterable.c \
../src/AList_test_prune.c \
../src/AList_test_prune_and_dispose.c \
../src/AList_test_prune_first.c \
../src/AList_test_prune_first_and_dispose.c \
../src/AList_test_prune_last.c \
../src/AList_test_prune_last_and_dispose.c \
../src/AList_test_put.c \
../src/AList_test_put_first.c \
../src/AList_test_put_last.c \
../src/AList_test_put_left.c \
../src/AList_test_put_right.c \
../src/AList_test_remove.c \
../src/AList_test_remove_and_dispose.c \
../src/AList_test_remove_at.c \
../src/AList_test_remove_at_and_dispose.c \
../src/AList_test_remove_first.c \
../src/AList_test_remove_first_and_dispose.c \
../src/AList_test_remove_last.c \
../src/AList_test_remove_last_and_dispose.c \
../src/AList_test_replace.c \
../src/AList_test_replace_and_dispose.c \
../src/AList_test_replace_at.c \
../src/AList_test_replace_at_and_dispose.c \
../src/AList_test_sort.c \
../src/AList_test_start.c \
../src/AList_test_wipe_out.c \
../src/AList_test_wipe_out_and_dispose.c \
../src/i_Clonable.c \
../src/i_DIterable.c \
../src/i_Indexable.c \
../src/i_Iterable.c \
../src/int_AList.c \
../src/main.c 

OBJS += \
./src/AList_test_append.o \
./src/AList_test_append_first.o \
./src/AList_test_append_last.o \
./src/AList_test_append_left.o \
./src/AList_test_append_right.o \
./src/AList_test_as_array.o \
./src/AList_test_back.o \
./src/AList_test_count.o \
./src/AList_test_cursor_append_left.o \
./src/AList_test_cursor_append_right.o \
./src/AList_test_cursor_back.o \
./src/AList_test_cursor_dispose.o \
./src/AList_test_cursor_finish.o \
./src/AList_test_cursor_forth.o \
./src/AList_test_cursor_go.o \
./src/AList_test_cursor_index.o \
./src/AList_test_cursor_is_first.o \
./src/AList_test_cursor_is_last.o \
./src/AList_test_cursor_item_at.o \
./src/AList_test_cursor_item_next.o \
./src/AList_test_cursor_item_prev.o \
./src/AList_test_cursor_make.o \
./src/AList_test_cursor_off.o \
./src/AList_test_cursor_put_left.o \
./src/AList_test_cursor_put_right.o \
./src/AList_test_cursor_remove_at.o \
./src/AList_test_cursor_remove_at_and_dispose.o \
./src/AList_test_cursor_replace_at.o \
./src/AList_test_cursor_replace_at_and_dispose.o \
./src/AList_test_cursor_start.o \
./src/AList_test_dispose.o \
./src/AList_test_dispose_with_contents.o \
./src/AList_test_finish.o \
./src/AList_test_first.o \
./src/AList_test_forth.o \
./src/AList_test_go.o \
./src/AList_test_index.o \
./src/AList_test_is_empty.o \
./src/AList_test_is_first.o \
./src/AList_test_is_last.o \
./src/AList_test_item.o \
./src/AList_test_item_at.o \
./src/AList_test_item_next.o \
./src/AList_test_item_prev.o \
./src/AList_test_keep_first.o \
./src/AList_test_keep_first_and_dispose.o \
./src/AList_test_keep_last.o \
./src/AList_test_keep_last_and_dispose.o \
./src/AList_test_last.o \
./src/AList_test_make.o \
./src/AList_test_make_duplicate_from.o \
./src/AList_test_make_from.o \
./src/AList_test_make_from_array.o \
./src/AList_test_off.o \
./src/AList_test_p_clonable.o \
./src/AList_test_p_diterable.o \
./src/AList_test_p_indexable.o \
./src/AList_test_p_iterable.o \
./src/AList_test_prune.o \
./src/AList_test_prune_and_dispose.o \
./src/AList_test_prune_first.o \
./src/AList_test_prune_first_and_dispose.o \
./src/AList_test_prune_last.o \
./src/AList_test_prune_last_and_dispose.o \
./src/AList_test_put.o \
./src/AList_test_put_first.o \
./src/AList_test_put_last.o \
./src/AList_test_put_left.o \
./src/AList_test_put_right.o \
./src/AList_test_remove.o \
./src/AList_test_remove_and_dispose.o \
./src/AList_test_remove_at.o \
./src/AList_test_remove_at_and_dispose.o \
./src/AList_test_remove_first.o \
./src/AList_test_remove_first_and_dispose.o \
./src/AList_test_remove_last.o \
./src/AList_test_remove_last_and_dispose.o \
./src/AList_test_replace.o \
./src/AList_test_replace_and_dispose.o \
./src/AList_test_replace_at.o \
./src/AList_test_replace_at_and_dispose.o \
./src/AList_test_sort.o \
./src/AList_test_start.o \
./src/AList_test_wipe_out.o \
./src/AList_test_wipe_out_and_dispose.o \
./src/i_Clonable.o \
./src/i_DIterable.o \
./src/i_Indexable.o \
./src/i_Iterable.o \
./src/int_AList.o \
./src/main.o 

C_DEPS += \
./src/AList_test_append.d \
./src/AList_test_append_first.d \
./src/AList_test_append_last.d \
./src/AList_test_append_left.d \
./src/AList_test_append_right.d \
./src/AList_test_as_array.d \
./src/AList_test_back.d \
./src/AList_test_count.d \
./src/AList_test_cursor_append_left.d \
./src/AList_test_cursor_append_right.d \
./src/AList_test_cursor_back.d \
./src/AList_test_cursor_dispose.d \
./src/AList_test_cursor_finish.d \
./src/AList_test_cursor_forth.d \
./src/AList_test_cursor_go.d \
./src/AList_test_cursor_index.d \
./src/AList_test_cursor_is_first.d \
./src/AList_test_cursor_is_last.d \
./src/AList_test_cursor_item_at.d \
./src/AList_test_cursor_item_next.d \
./src/AList_test_cursor_item_prev.d \
./src/AList_test_cursor_make.d \
./src/AList_test_cursor_off.d \
./src/AList_test_cursor_put_left.d \
./src/AList_test_cursor_put_right.d \
./src/AList_test_cursor_remove_at.d \
./src/AList_test_cursor_remove_at_and_dispose.d \
./src/AList_test_cursor_replace_at.d \
./src/AList_test_cursor_replace_at_and_dispose.d \
./src/AList_test_cursor_start.d \
./src/AList_test_dispose.d \
./src/AList_test_dispose_with_contents.d \
./src/AList_test_finish.d \
./src/AList_test_first.d \
./src/AList_test_forth.d \
./src/AList_test_go.d \
./src/AList_test_index.d \
./src/AList_test_is_empty.d \
./src/AList_test_is_first.d \
./src/AList_test_is_last.d \
./src/AList_test_item.d \
./src/AList_test_item_at.d \
./src/AList_test_item_next.d \
./src/AList_test_item_prev.d \
./src/AList_test_keep_first.d \
./src/AList_test_keep_first_and_dispose.d \
./src/AList_test_keep_last.d \
./src/AList_test_keep_last_and_dispose.d \
./src/AList_test_last.d \
./src/AList_test_make.d \
./src/AList_test_make_duplicate_from.d \
./src/AList_test_make_from.d \
./src/AList_test_make_from_array.d \
./src/AList_test_off.d \
./src/AList_test_p_clonable.d \
./src/AList_test_p_diterable.d \
./src/AList_test_p_indexable.d \
./src/AList_test_p_iterable.d \
./src/AList_test_prune.d \
./src/AList_test_prune_and_dispose.d \
./src/AList_test_prune_first.d \
./src/AList_test_prune_first_and_dispose.d \
./src/AList_test_prune_last.d \
./src/AList_test_prune_last_and_dispose.d \
./src/AList_test_put.d \
./src/AList_test_put_first.d \
./src/AList_test_put_last.d \
./src/AList_test_put_left.d \
./src/AList_test_put_right.d \
./src/AList_test_remove.d \
./src/AList_test_remove_and_dispose.d \
./src/AList_test_remove_at.d \
./src/AList_test_remove_at_and_dispose.d \
./src/AList_test_remove_first.d \
./src/AList_test_remove_first_and_dispose.d \
./src/AList_test_remove_last.d \
./src/AList_test_remove_last_and_dispose.d \
./src/AList_test_replace.d \
./src/AList_test_replace_and_dispose.d \
./src/AList_test_replace_at.d \
./src/AList_test_replace_at_and_dispose.d \
./src/AList_test_sort.d \
./src/AList_test_start.d \
./src/AList_test_wipe_out.d \
./src/AList_test_wipe_out_and_dispose.d \
./src/i_Clonable.d \
./src/i_DIterable.d \
./src/i_Indexable.d \
./src/i_Iterable.d \
./src/int_AList.d \
./src/main.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I../../../base -I../../../dbc -I../../../AList -I../../../Protocol_Base -I../../../P_Indexable -I../../../P_Iterable -I../../../P_DIterable -I../../../P_Clonable -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


