################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/DGraph_test_are_adjacent.c \
../src/DGraph_test_as_array.c \
../src/DGraph_test_at.c \
../src/DGraph_test_count.c \
../src/DGraph_test_cursor_at.c \
../src/DGraph_test_cursor_dispose.c \
../src/DGraph_test_cursor_edge_at.c \
../src/DGraph_test_cursor_edge_find_next_value.c \
../src/DGraph_test_cursor_edge_find_value.c \
../src/DGraph_test_cursor_edge_forth.c \
../src/DGraph_test_cursor_edge_off.c \
../src/DGraph_test_cursor_edge_start.c \
../src/DGraph_test_cursor_edge_value_at.c \
../src/DGraph_test_cursor_find_next_value.c \
../src/DGraph_test_cursor_find_value.c \
../src/DGraph_test_cursor_forth.c \
../src/DGraph_test_cursor_make_breadth.c \
../src/DGraph_test_cursor_make_depth.c \
../src/DGraph_test_cursor_off.c \
../src/DGraph_test_cursor_start.c \
../src/DGraph_test_cursor_value_at.c \
../src/DGraph_test_dispose.c \
../src/DGraph_test_dispose_with_contents.c \
../src/DGraph_test_edge_at.c \
../src/DGraph_test_edge_count.c \
../src/DGraph_test_edge_find_next_value.c \
../src/DGraph_test_edge_find_value.c \
../src/DGraph_test_edge_forth.c \
../src/DGraph_test_edge_from_to.c \
../src/DGraph_test_edge_has.c \
../src/DGraph_test_edge_has_value.c \
../src/DGraph_test_edge_is_empty.c \
../src/DGraph_test_edge_off.c \
../src/DGraph_test_edge_put.c \
../src/DGraph_test_edge_remove.c \
../src/DGraph_test_edge_remove_and_dispose.c \
../src/DGraph_test_edge_remove_and_dispose_from_to.c \
../src/DGraph_test_edge_remove_from_to.c \
../src/DGraph_test_edge_set.c \
../src/DGraph_test_edge_set_bucket_count.c \
../src/DGraph_test_edge_set_value.c \
../src/DGraph_test_edge_start.c \
../src/DGraph_test_edge_value.c \
../src/DGraph_test_edge_value_at.c \
../src/DGraph_test_edge_value_from_to.c \
../src/DGraph_test_edge_vertex_from.c \
../src/DGraph_test_edge_vertex_to.c \
../src/DGraph_test_edge_wipe_out.c \
../src/DGraph_test_edge_wipe_out_and_dispose.c \
../src/DGraph_test_edges_as_array.c \
../src/DGraph_test_find_next_value.c \
../src/DGraph_test_find_value.c \
../src/DGraph_test_forth.c \
../src/DGraph_test_has.c \
../src/DGraph_test_has_value.c \
../src/DGraph_test_is_connected.c \
../src/DGraph_test_is_empty.c \
../src/DGraph_test_make_breadth.c \
../src/DGraph_test_make_depth.c \
../src/DGraph_test_neighbors_from.c \
../src/DGraph_test_neighbors_to.c \
../src/DGraph_test_off.c \
../src/DGraph_test_put.c \
../src/DGraph_test_remove.c \
../src/DGraph_test_remove_and_dispose.c \
../src/DGraph_test_set_value.c \
../src/DGraph_test_start.c \
../src/DGraph_test_value.c \
../src/DGraph_test_value_at.c \
../src/DGraph_test_vertex_dispose.c \
../src/DGraph_test_vertex_dispose_with_contents.c \
../src/DGraph_test_vertex_make.c \
../src/DGraph_test_vertex_set_bucket_count.c \
../src/DGraph_test_wipe_out.c \
../src/DGraph_test_wipe_out_and_dispose.c \
../src/i_dgraph_edge_HSet.c \
../src/i_dgraph_vertex_HSet.c \
../src/ii_DGraph.c \
../src/main.c 

OBJS += \
./src/DGraph_test_are_adjacent.o \
./src/DGraph_test_as_array.o \
./src/DGraph_test_at.o \
./src/DGraph_test_count.o \
./src/DGraph_test_cursor_at.o \
./src/DGraph_test_cursor_dispose.o \
./src/DGraph_test_cursor_edge_at.o \
./src/DGraph_test_cursor_edge_find_next_value.o \
./src/DGraph_test_cursor_edge_find_value.o \
./src/DGraph_test_cursor_edge_forth.o \
./src/DGraph_test_cursor_edge_off.o \
./src/DGraph_test_cursor_edge_start.o \
./src/DGraph_test_cursor_edge_value_at.o \
./src/DGraph_test_cursor_find_next_value.o \
./src/DGraph_test_cursor_find_value.o \
./src/DGraph_test_cursor_forth.o \
./src/DGraph_test_cursor_make_breadth.o \
./src/DGraph_test_cursor_make_depth.o \
./src/DGraph_test_cursor_off.o \
./src/DGraph_test_cursor_start.o \
./src/DGraph_test_cursor_value_at.o \
./src/DGraph_test_dispose.o \
./src/DGraph_test_dispose_with_contents.o \
./src/DGraph_test_edge_at.o \
./src/DGraph_test_edge_count.o \
./src/DGraph_test_edge_find_next_value.o \
./src/DGraph_test_edge_find_value.o \
./src/DGraph_test_edge_forth.o \
./src/DGraph_test_edge_from_to.o \
./src/DGraph_test_edge_has.o \
./src/DGraph_test_edge_has_value.o \
./src/DGraph_test_edge_is_empty.o \
./src/DGraph_test_edge_off.o \
./src/DGraph_test_edge_put.o \
./src/DGraph_test_edge_remove.o \
./src/DGraph_test_edge_remove_and_dispose.o \
./src/DGraph_test_edge_remove_and_dispose_from_to.o \
./src/DGraph_test_edge_remove_from_to.o \
./src/DGraph_test_edge_set.o \
./src/DGraph_test_edge_set_bucket_count.o \
./src/DGraph_test_edge_set_value.o \
./src/DGraph_test_edge_start.o \
./src/DGraph_test_edge_value.o \
./src/DGraph_test_edge_value_at.o \
./src/DGraph_test_edge_value_from_to.o \
./src/DGraph_test_edge_vertex_from.o \
./src/DGraph_test_edge_vertex_to.o \
./src/DGraph_test_edge_wipe_out.o \
./src/DGraph_test_edge_wipe_out_and_dispose.o \
./src/DGraph_test_edges_as_array.o \
./src/DGraph_test_find_next_value.o \
./src/DGraph_test_find_value.o \
./src/DGraph_test_forth.o \
./src/DGraph_test_has.o \
./src/DGraph_test_has_value.o \
./src/DGraph_test_is_connected.o \
./src/DGraph_test_is_empty.o \
./src/DGraph_test_make_breadth.o \
./src/DGraph_test_make_depth.o \
./src/DGraph_test_neighbors_from.o \
./src/DGraph_test_neighbors_to.o \
./src/DGraph_test_off.o \
./src/DGraph_test_put.o \
./src/DGraph_test_remove.o \
./src/DGraph_test_remove_and_dispose.o \
./src/DGraph_test_set_value.o \
./src/DGraph_test_start.o \
./src/DGraph_test_value.o \
./src/DGraph_test_value_at.o \
./src/DGraph_test_vertex_dispose.o \
./src/DGraph_test_vertex_dispose_with_contents.o \
./src/DGraph_test_vertex_make.o \
./src/DGraph_test_vertex_set_bucket_count.o \
./src/DGraph_test_wipe_out.o \
./src/DGraph_test_wipe_out_and_dispose.o \
./src/i_dgraph_edge_HSet.o \
./src/i_dgraph_vertex_HSet.o \
./src/ii_DGraph.o \
./src/main.o 

C_DEPS += \
./src/DGraph_test_are_adjacent.d \
./src/DGraph_test_as_array.d \
./src/DGraph_test_at.d \
./src/DGraph_test_count.d \
./src/DGraph_test_cursor_at.d \
./src/DGraph_test_cursor_dispose.d \
./src/DGraph_test_cursor_edge_at.d \
./src/DGraph_test_cursor_edge_find_next_value.d \
./src/DGraph_test_cursor_edge_find_value.d \
./src/DGraph_test_cursor_edge_forth.d \
./src/DGraph_test_cursor_edge_off.d \
./src/DGraph_test_cursor_edge_start.d \
./src/DGraph_test_cursor_edge_value_at.d \
./src/DGraph_test_cursor_find_next_value.d \
./src/DGraph_test_cursor_find_value.d \
./src/DGraph_test_cursor_forth.d \
./src/DGraph_test_cursor_make_breadth.d \
./src/DGraph_test_cursor_make_depth.d \
./src/DGraph_test_cursor_off.d \
./src/DGraph_test_cursor_start.d \
./src/DGraph_test_cursor_value_at.d \
./src/DGraph_test_dispose.d \
./src/DGraph_test_dispose_with_contents.d \
./src/DGraph_test_edge_at.d \
./src/DGraph_test_edge_count.d \
./src/DGraph_test_edge_find_next_value.d \
./src/DGraph_test_edge_find_value.d \
./src/DGraph_test_edge_forth.d \
./src/DGraph_test_edge_from_to.d \
./src/DGraph_test_edge_has.d \
./src/DGraph_test_edge_has_value.d \
./src/DGraph_test_edge_is_empty.d \
./src/DGraph_test_edge_off.d \
./src/DGraph_test_edge_put.d \
./src/DGraph_test_edge_remove.d \
./src/DGraph_test_edge_remove_and_dispose.d \
./src/DGraph_test_edge_remove_and_dispose_from_to.d \
./src/DGraph_test_edge_remove_from_to.d \
./src/DGraph_test_edge_set.d \
./src/DGraph_test_edge_set_bucket_count.d \
./src/DGraph_test_edge_set_value.d \
./src/DGraph_test_edge_start.d \
./src/DGraph_test_edge_value.d \
./src/DGraph_test_edge_value_at.d \
./src/DGraph_test_edge_value_from_to.d \
./src/DGraph_test_edge_vertex_from.d \
./src/DGraph_test_edge_vertex_to.d \
./src/DGraph_test_edge_wipe_out.d \
./src/DGraph_test_edge_wipe_out_and_dispose.d \
./src/DGraph_test_edges_as_array.d \
./src/DGraph_test_find_next_value.d \
./src/DGraph_test_find_value.d \
./src/DGraph_test_forth.d \
./src/DGraph_test_has.d \
./src/DGraph_test_has_value.d \
./src/DGraph_test_is_connected.d \
./src/DGraph_test_is_empty.d \
./src/DGraph_test_make_breadth.d \
./src/DGraph_test_make_depth.d \
./src/DGraph_test_neighbors_from.d \
./src/DGraph_test_neighbors_to.d \
./src/DGraph_test_off.d \
./src/DGraph_test_put.d \
./src/DGraph_test_remove.d \
./src/DGraph_test_remove_and_dispose.d \
./src/DGraph_test_set_value.d \
./src/DGraph_test_start.d \
./src/DGraph_test_value.d \
./src/DGraph_test_value_at.d \
./src/DGraph_test_vertex_dispose.d \
./src/DGraph_test_vertex_dispose_with_contents.d \
./src/DGraph_test_vertex_make.d \
./src/DGraph_test_vertex_set_bucket_count.d \
./src/DGraph_test_wipe_out.d \
./src/DGraph_test_wipe_out_and_dispose.d \
./src/i_dgraph_edge_HSet.d \
./src/i_dgraph_vertex_HSet.d \
./src/ii_DGraph.d \
./src/main.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I../../../base -I../../../dbc -I../../../DGraph -I../../../HSet -I../../../Protocol_Base -I../../../P_Clonable -I../../../P_Iterable -O0 -g3 -ftest-coverage -fprofile-arcs -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


