################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/UGraph_test_are_adjacent.c \
../src/UGraph_test_as_array.c \
../src/UGraph_test_at.c \
../src/UGraph_test_count.c \
../src/UGraph_test_cursor_at.c \
../src/UGraph_test_cursor_dispose.c \
../src/UGraph_test_cursor_edge_at.c \
../src/UGraph_test_cursor_edge_find_next_value.c \
../src/UGraph_test_cursor_edge_find_value.c \
../src/UGraph_test_cursor_edge_forth.c \
../src/UGraph_test_cursor_edge_off.c \
../src/UGraph_test_cursor_edge_start.c \
../src/UGraph_test_cursor_edge_value_at.c \
../src/UGraph_test_cursor_find_next_value.c \
../src/UGraph_test_cursor_find_value.c \
../src/UGraph_test_cursor_forth.c \
../src/UGraph_test_cursor_make_breadth.c \
../src/UGraph_test_cursor_make_depth.c \
../src/UGraph_test_cursor_off.c \
../src/UGraph_test_cursor_start.c \
../src/UGraph_test_cursor_value_at.c \
../src/UGraph_test_dispose.c \
../src/UGraph_test_dispose_with_contents.c \
../src/UGraph_test_edge_at.c \
../src/UGraph_test_edge_count.c \
../src/UGraph_test_edge_find_next_value.c \
../src/UGraph_test_edge_find_value.c \
../src/UGraph_test_edge_forth.c \
../src/UGraph_test_edge_has.c \
../src/UGraph_test_edge_has_value.c \
../src/UGraph_test_edge_is_empty.c \
../src/UGraph_test_edge_off.c \
../src/UGraph_test_edge_put.c \
../src/UGraph_test_edge_remove.c \
../src/UGraph_test_edge_remove_and_dispose.c \
../src/UGraph_test_edge_remove_and_dispose_v1_v2.c \
../src/UGraph_test_edge_remove_v1_v2.c \
../src/UGraph_test_edge_set.c \
../src/UGraph_test_edge_set_bucket_count.c \
../src/UGraph_test_edge_set_value.c \
../src/UGraph_test_edge_start.c \
../src/UGraph_test_edge_v1.c \
../src/UGraph_test_edge_v1_v2.c \
../src/UGraph_test_edge_v2.c \
../src/UGraph_test_edge_value.c \
../src/UGraph_test_edge_value_at.c \
../src/UGraph_test_edge_value_v1_v2.c \
../src/UGraph_test_edge_wipe_out.c \
../src/UGraph_test_edge_wipe_out_and_dispose.c \
../src/UGraph_test_edges_as_array.c \
../src/UGraph_test_find_next_value.c \
../src/UGraph_test_find_value.c \
../src/UGraph_test_forth.c \
../src/UGraph_test_has.c \
../src/UGraph_test_has_value.c \
../src/UGraph_test_is_connected.c \
../src/UGraph_test_is_empty.c \
../src/UGraph_test_make_breadth.c \
../src/UGraph_test_make_depth.c \
../src/UGraph_test_neighbors.c \
../src/UGraph_test_off.c \
../src/UGraph_test_put.c \
../src/UGraph_test_remove.c \
../src/UGraph_test_remove_and_dispose.c \
../src/UGraph_test_set_value.c \
../src/UGraph_test_start.c \
../src/UGraph_test_value.c \
../src/UGraph_test_value_at.c \
../src/UGraph_test_vertex_dispose.c \
../src/UGraph_test_vertex_dispose_with_contents.c \
../src/UGraph_test_vertex_make.c \
../src/UGraph_test_vertex_set_bucket_count.c \
../src/UGraph_test_wipe_out.c \
../src/UGraph_test_wipe_out_and_dispose.c \
../src/i_ugraph_edge_HSet.c \
../src/i_ugraph_vertex_HSet.c \
../src/ii_UGraph.c \
../src/main.c 

OBJS += \
./src/UGraph_test_are_adjacent.o \
./src/UGraph_test_as_array.o \
./src/UGraph_test_at.o \
./src/UGraph_test_count.o \
./src/UGraph_test_cursor_at.o \
./src/UGraph_test_cursor_dispose.o \
./src/UGraph_test_cursor_edge_at.o \
./src/UGraph_test_cursor_edge_find_next_value.o \
./src/UGraph_test_cursor_edge_find_value.o \
./src/UGraph_test_cursor_edge_forth.o \
./src/UGraph_test_cursor_edge_off.o \
./src/UGraph_test_cursor_edge_start.o \
./src/UGraph_test_cursor_edge_value_at.o \
./src/UGraph_test_cursor_find_next_value.o \
./src/UGraph_test_cursor_find_value.o \
./src/UGraph_test_cursor_forth.o \
./src/UGraph_test_cursor_make_breadth.o \
./src/UGraph_test_cursor_make_depth.o \
./src/UGraph_test_cursor_off.o \
./src/UGraph_test_cursor_start.o \
./src/UGraph_test_cursor_value_at.o \
./src/UGraph_test_dispose.o \
./src/UGraph_test_dispose_with_contents.o \
./src/UGraph_test_edge_at.o \
./src/UGraph_test_edge_count.o \
./src/UGraph_test_edge_find_next_value.o \
./src/UGraph_test_edge_find_value.o \
./src/UGraph_test_edge_forth.o \
./src/UGraph_test_edge_has.o \
./src/UGraph_test_edge_has_value.o \
./src/UGraph_test_edge_is_empty.o \
./src/UGraph_test_edge_off.o \
./src/UGraph_test_edge_put.o \
./src/UGraph_test_edge_remove.o \
./src/UGraph_test_edge_remove_and_dispose.o \
./src/UGraph_test_edge_remove_and_dispose_v1_v2.o \
./src/UGraph_test_edge_remove_v1_v2.o \
./src/UGraph_test_edge_set.o \
./src/UGraph_test_edge_set_bucket_count.o \
./src/UGraph_test_edge_set_value.o \
./src/UGraph_test_edge_start.o \
./src/UGraph_test_edge_v1.o \
./src/UGraph_test_edge_v1_v2.o \
./src/UGraph_test_edge_v2.o \
./src/UGraph_test_edge_value.o \
./src/UGraph_test_edge_value_at.o \
./src/UGraph_test_edge_value_v1_v2.o \
./src/UGraph_test_edge_wipe_out.o \
./src/UGraph_test_edge_wipe_out_and_dispose.o \
./src/UGraph_test_edges_as_array.o \
./src/UGraph_test_find_next_value.o \
./src/UGraph_test_find_value.o \
./src/UGraph_test_forth.o \
./src/UGraph_test_has.o \
./src/UGraph_test_has_value.o \
./src/UGraph_test_is_connected.o \
./src/UGraph_test_is_empty.o \
./src/UGraph_test_make_breadth.o \
./src/UGraph_test_make_depth.o \
./src/UGraph_test_neighbors.o \
./src/UGraph_test_off.o \
./src/UGraph_test_put.o \
./src/UGraph_test_remove.o \
./src/UGraph_test_remove_and_dispose.o \
./src/UGraph_test_set_value.o \
./src/UGraph_test_start.o \
./src/UGraph_test_value.o \
./src/UGraph_test_value_at.o \
./src/UGraph_test_vertex_dispose.o \
./src/UGraph_test_vertex_dispose_with_contents.o \
./src/UGraph_test_vertex_make.o \
./src/UGraph_test_vertex_set_bucket_count.o \
./src/UGraph_test_wipe_out.o \
./src/UGraph_test_wipe_out_and_dispose.o \
./src/i_ugraph_edge_HSet.o \
./src/i_ugraph_vertex_HSet.o \
./src/ii_UGraph.o \
./src/main.o 

C_DEPS += \
./src/UGraph_test_are_adjacent.d \
./src/UGraph_test_as_array.d \
./src/UGraph_test_at.d \
./src/UGraph_test_count.d \
./src/UGraph_test_cursor_at.d \
./src/UGraph_test_cursor_dispose.d \
./src/UGraph_test_cursor_edge_at.d \
./src/UGraph_test_cursor_edge_find_next_value.d \
./src/UGraph_test_cursor_edge_find_value.d \
./src/UGraph_test_cursor_edge_forth.d \
./src/UGraph_test_cursor_edge_off.d \
./src/UGraph_test_cursor_edge_start.d \
./src/UGraph_test_cursor_edge_value_at.d \
./src/UGraph_test_cursor_find_next_value.d \
./src/UGraph_test_cursor_find_value.d \
./src/UGraph_test_cursor_forth.d \
./src/UGraph_test_cursor_make_breadth.d \
./src/UGraph_test_cursor_make_depth.d \
./src/UGraph_test_cursor_off.d \
./src/UGraph_test_cursor_start.d \
./src/UGraph_test_cursor_value_at.d \
./src/UGraph_test_dispose.d \
./src/UGraph_test_dispose_with_contents.d \
./src/UGraph_test_edge_at.d \
./src/UGraph_test_edge_count.d \
./src/UGraph_test_edge_find_next_value.d \
./src/UGraph_test_edge_find_value.d \
./src/UGraph_test_edge_forth.d \
./src/UGraph_test_edge_has.d \
./src/UGraph_test_edge_has_value.d \
./src/UGraph_test_edge_is_empty.d \
./src/UGraph_test_edge_off.d \
./src/UGraph_test_edge_put.d \
./src/UGraph_test_edge_remove.d \
./src/UGraph_test_edge_remove_and_dispose.d \
./src/UGraph_test_edge_remove_and_dispose_v1_v2.d \
./src/UGraph_test_edge_remove_v1_v2.d \
./src/UGraph_test_edge_set.d \
./src/UGraph_test_edge_set_bucket_count.d \
./src/UGraph_test_edge_set_value.d \
./src/UGraph_test_edge_start.d \
./src/UGraph_test_edge_v1.d \
./src/UGraph_test_edge_v1_v2.d \
./src/UGraph_test_edge_v2.d \
./src/UGraph_test_edge_value.d \
./src/UGraph_test_edge_value_at.d \
./src/UGraph_test_edge_value_v1_v2.d \
./src/UGraph_test_edge_wipe_out.d \
./src/UGraph_test_edge_wipe_out_and_dispose.d \
./src/UGraph_test_edges_as_array.d \
./src/UGraph_test_find_next_value.d \
./src/UGraph_test_find_value.d \
./src/UGraph_test_forth.d \
./src/UGraph_test_has.d \
./src/UGraph_test_has_value.d \
./src/UGraph_test_is_connected.d \
./src/UGraph_test_is_empty.d \
./src/UGraph_test_make_breadth.d \
./src/UGraph_test_make_depth.d \
./src/UGraph_test_neighbors.d \
./src/UGraph_test_off.d \
./src/UGraph_test_put.d \
./src/UGraph_test_remove.d \
./src/UGraph_test_remove_and_dispose.d \
./src/UGraph_test_set_value.d \
./src/UGraph_test_start.d \
./src/UGraph_test_value.d \
./src/UGraph_test_value_at.d \
./src/UGraph_test_vertex_dispose.d \
./src/UGraph_test_vertex_dispose_with_contents.d \
./src/UGraph_test_vertex_make.d \
./src/UGraph_test_vertex_set_bucket_count.d \
./src/UGraph_test_wipe_out.d \
./src/UGraph_test_wipe_out_and_dispose.d \
./src/i_ugraph_edge_HSet.d \
./src/i_ugraph_vertex_HSet.d \
./src/ii_UGraph.d \
./src/main.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I../../../base -I../../../dbc -I../../../UGraph -I../../../Protocol_Base -I../../../HSet -I../../../P_Clonable -I../../../P_Iterable -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


