################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/String_test_append.c \
../src/String_test_append_character.c \
../src/String_test_append_cstring.c \
../src/String_test_append_indent.c \
../src/String_test_append_newline.c \
../src/String_test_as_cstring.c \
../src/String_test_as_float64.c \
../src/String_test_as_int32.c \
../src/String_test_as_lower.c \
../src/String_test_as_upper.c \
../src/String_test_capacity.c \
../src/String_test_copy.c \
../src/String_test_count.c \
../src/String_test_cstring_hex_from_int32.c \
../src/String_test_cstring_hex_from_uint8.c \
../src/String_test_cstring_hex_to_uint8.c \
../src/String_test_cstring_to_file_cstring.c \
../src/String_test_current_time.c \
../src/String_test_dispose.c \
../src/String_test_dispose_with_contents.c \
../src/String_test_ends_with.c \
../src/String_test_ends_with_cstring.c \
../src/String_test_extras.c \
../src/String_test_from_file.c \
../src/String_test_from_file_cstring.c \
../src/String_test_has.c \
../src/String_test_has_substring.c \
../src/String_test_has_substring_cstring.c \
../src/String_test_hash_code.c \
../src/String_test_hex_from_int32.c \
../src/String_test_hex_from_uint8.c \
../src/String_test_hex_to_uint8.c \
../src/String_test_insert.c \
../src/String_test_insert_character.c \
../src/String_test_insert_cstring.c \
../src/String_test_insert_float64.c \
../src/String_test_insert_int32.c \
../src/String_test_is_empty.c \
../src/String_test_is_equal.c \
../src/String_test_is_equal_cstring.c \
../src/String_test_is_float64.c \
../src/String_test_is_greater_than.c \
../src/String_test_is_greater_than_cstring.c \
../src/String_test_is_int32.c \
../src/String_test_is_less_than.c \
../src/String_test_is_less_than_cstring.c \
../src/String_test_item.c \
../src/String_test_keep_head.c \
../src/String_test_keep_tail.c \
../src/String_test_make.c \
../src/String_test_make_from.c \
../src/String_test_make_from_cstring.c \
../src/String_test_make_n.c \
../src/String_test_prepend.c \
../src/String_test_prepend_character.c \
../src/String_test_prepend_cstring.c \
../src/String_test_put.c \
../src/String_test_remove.c \
../src/String_test_remove_head.c \
../src/String_test_remove_substring.c \
../src/String_test_remove_tail.c \
../src/String_test_replace.c \
../src/String_test_replace_all.c \
../src/String_test_replace_all_cstring.c \
../src/String_test_replace_all_cstring2.c \
../src/String_test_replace_cstring.c \
../src/String_test_resize.c \
../src/String_test_split.c \
../src/String_test_split_cstring.c \
../src/String_test_starts_with.c \
../src/String_test_starts_with_cstring.c \
../src/String_test_substring.c \
../src/String_test_substring_index.c \
../src/String_test_substring_index_cstring.c \
../src/String_test_substring_index_in_bounds.c \
../src/String_test_substring_index_in_bounds_cstring.c \
../src/String_test_to_file.c \
../src/String_test_to_file_cstring.c \
../src/String_test_to_lower.c \
../src/String_test_to_upper.c \
../src/String_test_valid_index.c \
../src/String_test_wipe_out.c \
../src/main.c 

OBJS += \
./src/String_test_append.o \
./src/String_test_append_character.o \
./src/String_test_append_cstring.o \
./src/String_test_append_indent.o \
./src/String_test_append_newline.o \
./src/String_test_as_cstring.o \
./src/String_test_as_float64.o \
./src/String_test_as_int32.o \
./src/String_test_as_lower.o \
./src/String_test_as_upper.o \
./src/String_test_capacity.o \
./src/String_test_copy.o \
./src/String_test_count.o \
./src/String_test_cstring_hex_from_int32.o \
./src/String_test_cstring_hex_from_uint8.o \
./src/String_test_cstring_hex_to_uint8.o \
./src/String_test_cstring_to_file_cstring.o \
./src/String_test_current_time.o \
./src/String_test_dispose.o \
./src/String_test_dispose_with_contents.o \
./src/String_test_ends_with.o \
./src/String_test_ends_with_cstring.o \
./src/String_test_extras.o \
./src/String_test_from_file.o \
./src/String_test_from_file_cstring.o \
./src/String_test_has.o \
./src/String_test_has_substring.o \
./src/String_test_has_substring_cstring.o \
./src/String_test_hash_code.o \
./src/String_test_hex_from_int32.o \
./src/String_test_hex_from_uint8.o \
./src/String_test_hex_to_uint8.o \
./src/String_test_insert.o \
./src/String_test_insert_character.o \
./src/String_test_insert_cstring.o \
./src/String_test_insert_float64.o \
./src/String_test_insert_int32.o \
./src/String_test_is_empty.o \
./src/String_test_is_equal.o \
./src/String_test_is_equal_cstring.o \
./src/String_test_is_float64.o \
./src/String_test_is_greater_than.o \
./src/String_test_is_greater_than_cstring.o \
./src/String_test_is_int32.o \
./src/String_test_is_less_than.o \
./src/String_test_is_less_than_cstring.o \
./src/String_test_item.o \
./src/String_test_keep_head.o \
./src/String_test_keep_tail.o \
./src/String_test_make.o \
./src/String_test_make_from.o \
./src/String_test_make_from_cstring.o \
./src/String_test_make_n.o \
./src/String_test_prepend.o \
./src/String_test_prepend_character.o \
./src/String_test_prepend_cstring.o \
./src/String_test_put.o \
./src/String_test_remove.o \
./src/String_test_remove_head.o \
./src/String_test_remove_substring.o \
./src/String_test_remove_tail.o \
./src/String_test_replace.o \
./src/String_test_replace_all.o \
./src/String_test_replace_all_cstring.o \
./src/String_test_replace_all_cstring2.o \
./src/String_test_replace_cstring.o \
./src/String_test_resize.o \
./src/String_test_split.o \
./src/String_test_split_cstring.o \
./src/String_test_starts_with.o \
./src/String_test_starts_with_cstring.o \
./src/String_test_substring.o \
./src/String_test_substring_index.o \
./src/String_test_substring_index_cstring.o \
./src/String_test_substring_index_in_bounds.o \
./src/String_test_substring_index_in_bounds_cstring.o \
./src/String_test_to_file.o \
./src/String_test_to_file_cstring.o \
./src/String_test_to_lower.o \
./src/String_test_to_upper.o \
./src/String_test_valid_index.o \
./src/String_test_wipe_out.o \
./src/main.o 

C_DEPS += \
./src/String_test_append.d \
./src/String_test_append_character.d \
./src/String_test_append_cstring.d \
./src/String_test_append_indent.d \
./src/String_test_append_newline.d \
./src/String_test_as_cstring.d \
./src/String_test_as_float64.d \
./src/String_test_as_int32.d \
./src/String_test_as_lower.d \
./src/String_test_as_upper.d \
./src/String_test_capacity.d \
./src/String_test_copy.d \
./src/String_test_count.d \
./src/String_test_cstring_hex_from_int32.d \
./src/String_test_cstring_hex_from_uint8.d \
./src/String_test_cstring_hex_to_uint8.d \
./src/String_test_cstring_to_file_cstring.d \
./src/String_test_current_time.d \
./src/String_test_dispose.d \
./src/String_test_dispose_with_contents.d \
./src/String_test_ends_with.d \
./src/String_test_ends_with_cstring.d \
./src/String_test_extras.d \
./src/String_test_from_file.d \
./src/String_test_from_file_cstring.d \
./src/String_test_has.d \
./src/String_test_has_substring.d \
./src/String_test_has_substring_cstring.d \
./src/String_test_hash_code.d \
./src/String_test_hex_from_int32.d \
./src/String_test_hex_from_uint8.d \
./src/String_test_hex_to_uint8.d \
./src/String_test_insert.d \
./src/String_test_insert_character.d \
./src/String_test_insert_cstring.d \
./src/String_test_insert_float64.d \
./src/String_test_insert_int32.d \
./src/String_test_is_empty.d \
./src/String_test_is_equal.d \
./src/String_test_is_equal_cstring.d \
./src/String_test_is_float64.d \
./src/String_test_is_greater_than.d \
./src/String_test_is_greater_than_cstring.d \
./src/String_test_is_int32.d \
./src/String_test_is_less_than.d \
./src/String_test_is_less_than_cstring.d \
./src/String_test_item.d \
./src/String_test_keep_head.d \
./src/String_test_keep_tail.d \
./src/String_test_make.d \
./src/String_test_make_from.d \
./src/String_test_make_from_cstring.d \
./src/String_test_make_n.d \
./src/String_test_prepend.d \
./src/String_test_prepend_character.d \
./src/String_test_prepend_cstring.d \
./src/String_test_put.d \
./src/String_test_remove.d \
./src/String_test_remove_head.d \
./src/String_test_remove_substring.d \
./src/String_test_remove_tail.d \
./src/String_test_replace.d \
./src/String_test_replace_all.d \
./src/String_test_replace_all_cstring.d \
./src/String_test_replace_all_cstring2.d \
./src/String_test_replace_cstring.d \
./src/String_test_resize.d \
./src/String_test_split.d \
./src/String_test_split_cstring.d \
./src/String_test_starts_with.d \
./src/String_test_starts_with_cstring.d \
./src/String_test_substring.d \
./src/String_test_substring_index.d \
./src/String_test_substring_index_cstring.d \
./src/String_test_substring_index_in_bounds.d \
./src/String_test_substring_index_in_bounds_cstring.d \
./src/String_test_to_file.d \
./src/String_test_to_file_cstring.d \
./src/String_test_to_lower.d \
./src/String_test_to_upper.d \
./src/String_test_valid_index.d \
./src/String_test_wipe_out.d \
./src/main.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I../../../base -I../../../dbc -I../../../String -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


